-- CREATE DATABASE url_shortener;

CREATE TABLE urls(
  slug_id SERIAL PRIMARY KEY,
  slug VARCHAR(255) UNIQUE,
  url VARCHAR(255)
);
-- CREATE TABLE urls(slug_id SERIAL PRIMARY KEY,slug VARCHAR(255) UNIQUE,url VARCHAR(255));